CREATE TABLE Employees(
    Employee_id INT PRIMARY KEY,
    Name VARCHAR(100),
    Position VARCHAR(100),
    Salary INT
);

CREATE TABLE Employees_Audit(
	Audit_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Employee_id INT,
    Operation VARCHAR(10),
    Change_date DATE,
    Old_name VARCHAR(100),
    Old_position VARCHAR(100),
    Old_salary INT,
    New_name VARCHAR(100),
    New_position VARCHAR(100),
    New_salary INT
)

CREATE OR REPLACE FUNCTION Employees_Audit_Trigger()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        INSERT INTO Employees_Audit (
            Employee_id, Operation, Change_date,
            Old_name, Old_position, Old_salary,
            New_name, New_position, New_salary
        ) VALUES (
            NEW.Employee_id,
            TG_OP,
            CURRENT_DATE,
            NULL, NULL, NULL,  -- No old values on INSERT
            NEW.Name, NEW.Position, NEW.Salary
        );

    ELSIF TG_OP = 'UPDATE' THEN
        INSERT INTO Employees_Audit (
            Employee_id, Operation, Change_date,
            Old_name, Old_position, Old_salary,
            New_name, New_position, New_salary
        ) VALUES (
            NEW.Employee_id,
            TG_OP,
            CURRENT_DATE,
            OLD.Name, OLD.Position, OLD.Salary,
            NEW.Name, NEW.Position, NEW.Salary
        );

    ELSIF TG_OP = 'DELETE' THEN
        INSERT INTO Employees_Audit (
            Employee_id, Operation, Change_date,
            Old_name, Old_position, Old_salary,
            New_name, New_position, New_salary
        ) VALUES (
            OLD.Employee_id,
            TG_OP,
            CURRENT_DATE,
            OLD.Name, OLD.Position, OLD.Salary,
            NULL, NULL, NULL  -- No new values on DELETE
        );
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER employee_trigger
AFTER INSERT OR UPDATE OR DELETE on Employees
FOR EACH ROW
EXECUTE PROCEDURE Employees_Audit_Trigger();

-- Insert Queries
INSERT INTO Employees VALUES(1, 'Vivek', 'CEO', 690000);
INSERT INTO Employees VALUES(2, 'Vinay', 'CTO', 29000);
INSERT INTO Employees VALUES(3, 'Manju', 'HR', 10000);
INSERT INTO Employees VALUES(4, 'Manoj', 'IT', 20000);

-- Update Queries
UPDATE Employees SET Position='Finance' WHERE Employee_id=4;
UPDATE Employees SET Salary=43000 WHERE Employee_id=3;

-- DELETE Queries
DELETE FROM Employees WHERE Employee_id=4;


SELECT * FROM Employees_Audit;


